header-from: ./.config/header.md

version: ""

formatter: markdown table

name: terraform-aws-firehose-datadog-metrics-streaming

content: |-
  {{ .Header }}

  # terraform-aws-firehose-datadog-metrics-streaming

  GitHub: [StratusGrid/terraform-aws-datadog-metrics-streaming](https://github.com/StratusGrid/terraform-aws-datadog-metrics-streaming)

  This module creates a CloudWatch metrics stream and Firehose directed to a DataDog integration metrics ingest URL. For this reason, it disables datadog integrations which would be duplicated by a CloudWatch stream by default. The typical approach is to create one integration per account and one metrics stream per region (see example below).
  
  This is meant to be used with our module which creates the DataDog integration, which can be found here: [datadog-integration-streaming](https://registry.terraform.io/modules/StratusGrid/datadog-integration-streaming/aws/latest)

  ## Example
  
  Multi-region Example utilizing both the integration module to make the account level integration in DataDog and the metrics streaming module to create the Firehose and metrics stream in each region.
  ```hcl
  {{ include "examples/example-multi-region.tfnot" }}
  ```
  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`

sections:
  show:
    - header
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
